spring:
    mvc:
        log-request-details: true
    datasource:
        url: jdbc:mysql://localhost:3307/shark
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
                id:
                    new_generator_mappings: false

server:
    port: 8086 # This is the default port anyway, but you can change it here
logging:
    level:
        org:
            springframework:
                web: DEBUG
                security: DEBUG
